- hosts: main
  become: true
  roles:
    - hostname
    - essentials

  handlers:
    - name: restart systemd-networkd
      ansible.builtin.systemd:
        name: systemd-networkd
        state: restarted
