- hosts: main
  become: true
  roles:
    - hostname
    - essentials
    - security

  handlers:
    - name: restart systemd-networkd
      ansible.builtin.systemd:
        name: systemd-networkd
        state: restarted

    - name: restart netfilter-persistent
      ansible.builtin.systemd:
        name: netfilter-persistent
        state: restarted
