---
- name: Install packages
  ansible.builtin.apt:
    update_cache: yes
    name:
      - lxc
      - debootstrap
    state: present

- name: Copy default.conf
  ansible.builtin.copy:
    src: files/default.conf
    dest: /etc/lxc/default.conf
    owner: root
    group: root
    mode: '0644'

- name: Create backups directory
  ansible.builtin.file:
    path: /mnt/storage/backups/lxc
    owner: root
    group: root
    mode: '0700'
    state: directory

- name: backup script for lxc mail.spiraweb.pl
  ansible.builtin.copy:
    src: files/lxc-backup-mail-spiraweb-pl.sh
    dest: /root/scripts
    owner: root
    group: root
    mode: '700'

- name: .env-lxc-backups
  ansible.builtin.copy:
    src:  files/.env-lxc-backups
    dest: /root/scripts
    owner: root
    group: root
    mode: '600'

- name: add backup script for lxc mail.spiraweb.pl to cron
  ansible.builtin.cron:
    name: lxc mail.spiraweb.pl backup
    minute: "01"
    hour: "1"
    user: root
    job: "/root/scripts/lxc-backup-mail-spiraweb-pl.sh > /dev/null 2>&1"

- name: ensure lxc mail.spiraweb.pl is enabled at boot
  ansible.builtin.systemd:
    name: lxc@mail.spiraweb.pl
    enabled: yes
